### ISSUE TITLE
Url images

### ISSUE THREAD

**Issue by pedroconesa** [iviasensio/SmartCards#1]
Great extension!
I'm trying to get it working with url images with no luck.
In your example (Netflix.qvf) you're using images from the content library, but this is not a good solution for me because I'd need to upload thousands of images to the library manually. 

When I change the extension's images source to "image from Url" a new property box for the Url should appear, but it won't.
Am I doing something wrong?
Thanks in advance!

**Comment by iviasensio** [comment]
Hi Pedro
Just need to add a valid url, readable from your QS Server, i.e., try this url in the Netflix app:
**https://publicqssaasbucket.s3.eu-west-1.amazonaws.com/Netflix/**
... and nothing else, the extension will add internally the name of the image according to the dimension elements (do not forget to add the right image extension for your case)
Hope this helps

**Comment by iviasensio** [comment]
> Great extension! I'm trying to get it working with url images with no luck. In your example (Netflix.qvf) you're using images from the content library, but this is not a good solution for me because I'd need to upload thousands of images to the library manually.
> 
> When I change the extension's images source to "image from Url" a new property box for the Url should appear, but it won't. Am I doing something wrong? Thanks in advance!

About my previous comment... I asumed you use QS Server. If you use a SaaS version then you have to grant access to AWS buckets, so need to add a new content security policy in the management console.
Allow this url : publicqssaasbucket.s3.eu-west-1.amazonaws.com, only for the img-src tag.
![image](https://user-images.githubusercontent.com/11334576/162385124-9a831b77-43ed-4438-b2fa-2fcdbabefe89.png)

Regards

**Comment by pedroconesa** [comment]
Hi Ivan

But, where am I supposed to set that URL?
There's no extension's property where to be set. Does the extension need a
variable?
By the way, I'm using the lastest version of QSense (February 2022 patch 2)

Also my images may have both jpg and png formats. Could I set the image
extension property as an expression to check the file extension for every
dimension value or is it supposed to be global for the extension?

Thanks in advance

**Comment by iviasensio** [comment]
> https://publicqssaasbucket.s3.eu-west-1.amazonaws.com/Netflix/

There is a URL option as well as others, to indicate where do your images come from
![image](https://user-images.githubusercontent.com/11334576/162973499-e8f77e8f-3c3e-4ef9-a19d-5e2b3435d157.png)

The extension just allow 1 type of extension for images at the same time, but you can ping me directly by email explaining the business case and details about the Qlik customer and then I'll evaluate if it deserves dedicating more time and add this extra feature.
Regards

**Comment by pedroconesa** [comment]
Hi Ivan

In then snapshot you include in your last message (sorry, I didn't have the chance to answer you until now) there is a "Image url" box that doesn't appear to me:
![image](https://user-images.githubusercontent.com/42514516/167666976-4e8e4d16-3668-48ce-9890-f35ffe8a8fa0.png)

I'm using Qlik Sense February 2022. May be there's a problem with my version? or may be I've to check some other option I'm missing?

About my business case, I'm trying to show pictures of a product catalog and that catalog may use .png and .jpg images.
I'm loading a table with the url including file name and extension so I always know the file extension before it's shown.
Of course I can try to always have images in the same format (using some took to always keep the file in one format) but that would cost an extra disk space.

Thanks in advance!

**Comment by iviasensio** [comment]
Hi Again

First of all, please just download the latest version of the SmartCards extension to be sure you have all the features available.
I've just uploaded some improvements to allow that:
- just ensure that you add the full name of the image in the dimension, including the .png, .jpg, i.e. =MyImageField (where MyImageField = ImageName.png or ImageName.jpg) 
- and let it blank the 'Image Extension' setting

regards

**Comment by pedroconesa** [comment]
Thanks Ivan

Works great! 
For future versions would be fantastic if you could force image background. In your example (Netflix) all images were squares with no alpha channel for background. If we use images with transparent background the kpis behind the images are partially visible so it's not possible to recreate the fantastic hover effect that you implemented in the Netflix app.

![image](https://user-images.githubusercontent.com/42514516/168622145-cb824e66-7fc1-4e80-8beb-15aa33b4d98e.png)

Thanks indeed!

**Comment by iviasensio** [comment]
Alright, I'll keep it in mind
